name: VDSP CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install GTest
        run: |
          sudo apt-get install libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
      - name: Install libboost
        run: sudo apt-get install libboost-all-dev -y

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Build project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target VDSProject_test